In [2]:
import pandas as pd
import numpy as np

In [3]:
df_apart = pd.read_csv('apartments_for_rent_classified_10K.csv', encoding = 'latin', sep=';')
df_apart.head(3)

,id,category,title,body,amenities,bathrooms,bedrooms,currency,fee,has_photo,...,price_display,price_type,square_feet,address,cityname,state,latitude,longitude,source,time
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,$790,Monthly,101,NaN,Washington,DC,38.9057,-76.9861,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,$425,Monthly,106,814 Schutte Rd,Evansville,IN,37.9680,-87.6621,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,"$1,390",Monthly,107,NaN,Arlington,VA,38.8910,-77.0816,RentLingo,1577359410

In [4]:
df_apart.shape

(10000, 22)

In [5]:
df_apart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             10000 non-null  int64
 1   category       10000 non-null  object
 2   title          10000 non-null  object
 3   body           10000 non-null  object
 4   amenities      6451 non-null   object
 5   bathrooms      9966 non-null   float64
 6   bedrooms       9993 non-null   float64
 7   currency       10000 non-null  object
 8   fee            10000 non-null  object
 9   has_photo      10000 non-null  object
 10  pets_allowed   5837 non-null   object
 11  price          10000 non-null  int64
 12  price_display  10000 non-null  object
 13  price_type     10000 non-null  object
 14  square_feet    10000 non-null  int64
 15  address        6673 non-null   object
 16  cityname       9923 non-null   object
 17  state          9923 non-null   object
 18  latitude       9990 non-null   float64
 19  longitude      9990 non-null   float64
 20  source         10000 non-null  object
 21  time           10000 non-null  int64
dtypes: float64(4), int64(4), object(14)
memory usage: 1.7+ MB

In [6]:
df_apart.columns

Index(['id', 'category', 'title', 'body', 'amenities', 'bathrooms', 'bedrooms',
       'currency', 'fee', 'has_photo', 'pets_allowed', 'price',
       'price_display', 'price_type', 'square_feet', 'address', 'cityname',
       'state', 'latitude', 'longitude', 'source', 'time'],
      dtype='object')

In [10]:
df_apart.columns = ['id', 'categoria', 'título', 'corpo', 'comodidades', 'banheiros', 'quartos', 'moeda', 'taxa', 'com_foto', 'animais_permitidos', 'preço', 'exibição_de_preço', 'tipo_de_preço', 'metros_quadrados', 'endereço', 'nome_da_cidade',
'estado', 'latitude', 'longitude', 'origem', 'horário']
df_apart.head(3)

,id,categoria,título,corpo,comodidades,banheiros,quartos,moeda,taxa,com_foto,...,exibição_de_preço,tipo_de_preço,metros_quadrados,endereço,nome_da_cidade,estado,latitude,longitude,origem,horário
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,$790,Monthly,101,NaN,Washington,DC,38.9057,-76.9861,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,$425,Monthly,106,814 Schutte Rd,Evansville,IN,37.9680,-87.6621,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,"$1,390",Monthly,107,NaN,Arlington,VA,38.8910,-77.0816,RentLingo,1577359410

In [8]:
df_apart.isnull().sum()

id                       0
categoria                0
título                   0
corpo                    0
comodidades           3549
banheiros               34
quartos                  7
moeda                    0
taxa                     0
com_foto                 0
animais_permitidos    4163
preço                    0
exibição_de_preço        0
tipo_de_preço            0
metros_quadrados         0
endereço              3327
nome_da_cidade          77
estado                  77
latitude                10
longitude               10
origem                   0
horário                  0
dtype: int64

In [12]:
df_apart['exibição_de_preço'] = df_apart['exibição_de_preço'].str.replace('$', '').str.replace(',', '').str.replace('Weekly', '').str.replace('Monthly|', '').str.strip()
df_apart['exibição_de_preço'] = df_apart['exibição_de_preço'].astype(float)

In [13]:
df_apart.head(3)

,id,categoria,título,corpo,comodidades,banheiros,quartos,moeda,taxa,com_foto,...,exibição_de_preço,tipo_de_preço,metros_quadrados,endereço,nome_da_cidade,estado,latitude,longitude,origem,horário
0,5668626895,housing/rent/apartment,"Studio apartment 2nd St NE, Uhland Terrace NE,...","This unit is located at second St NE, Uhland T...",NaN,NaN,0.0,USD,No,Thumbnail,...,790.0,Monthly,101,NaN,Washington,DC,38.9057,-76.9861,RentLingo,1577359415
1,5664597177,housing/rent/apartment,Studio apartment 814 Schutte Road,"This unit is located at 814 Schutte Road, Evan...",NaN,NaN,1.0,USD,No,Thumbnail,...,425.0,Monthly,106,814 Schutte Rd,Evansville,IN,37.9680,-87.6621,RentLingo,1577017063
2,5668626833,housing/rent/apartment,"Studio apartment N Scott St, 14th St N, Arling...","This unit is located at N Scott St, 14th St N,...",NaN,1.0,0.0,USD,No,Thumbnail,...,1390.0,Monthly,107,NaN,Arlington,VA,38.8910,-77.0816,RentLingo,1577359410

In [14]:
df_apart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  10000 non-null  int64
 1   categoria           10000 non-null  object
 2   título              10000 non-null  object
 3   corpo               10000 non-null  object
 4   comodidades         6451 non-null   object
 5   banheiros           9966 non-null   float64
 6   quartos             9993 non-null   float64
 7   moeda               10000 non-null  object
 8   taxa                10000 non-null  object
 9   com_foto            10000 non-null  object
 10  animais_permitidos  5837 non-null   object
 11  preço               10000 non-null  int64
 12  exibição_de_preço   10000 non-null  float64
 13  tipo_de_preço       10000 non-null  object
 14  metros_quadrados    10000 non-null  int64
 15  endereço            6673 non-null   object
 16  nome_da_cidade      9923 non-null   object
 17  estado              9923 non-null   object
 18  latitude            9990 non-null   float64
 19  longitude           9990 non-null   float64
 20  origem              10000 non-null  object
 21  horário             10000 non-null  int64
dtypes: float64(5), int64(4), object(13)
memory usage: 1.7+ MB

In [20]:
df_apart['exibição_de_preço'].value_counts()

exibição_de_preço
1350.0    86
1250.0    81
850.0     79
1100.0    77
1400.0    74
          ..
1667.0     1
2053.0     1
813.0      1
1228.0     1
4790.0     1
Name: count, Length: 1725, dtype: int64

In [23]:
df_apart['quartos'].value_counts()

quartos
1.0    4607
2.0    3398
3.0    1276
4.0     404
0.0     198
5.0      89
6.0      15
7.0       3
8.0       2
9.0       1
Name: count, dtype: int64