O objetivo aqui é mostrar que você domina a sintaxe básica, sabe ler arquivos, limpar dados ausentes e criar gráficos simples.


Análise de Filmes e Séries (Netflix/IMDb):

- O que fazer: 
    - Descobrir quais são os gêneros mais comuns
    - a evolução dos lançamentos ao longo dos anos 
    - quais países produzem mais conteúdo.

- Bibliotecas: pandas, matplotlib, seaborn.
- Onde achar os dados: Netflix Movies and TV Shows no Kaggle.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df_netflix = pd.read_csv('netflix_titles_tmdb_enriched.csv')
df_netflix.head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,"Richard Johnson, Kirsten Johnson, Isla Sierck,...",United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,"Nosipho Dumisa-Ngoasheng, Daryne Joshua, Travi...","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","Belgium, France","September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [3]:
df_netflix.shape

(8807, 12)

In [4]:
df_netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      7604 non-null   object
 4   cast          8511 non-null   object
 5   country       8498 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8804 non-null   object
 9   duration      8807 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [6]:
df_netflix.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

In [32]:
lista = ['ID', 'Tipo', 'Título', 'Diretor', 'Elenco', 'País', 'Data de adição', 'Ano de lançamento', 'Classificação', 'duração', 'Listado em', 'Descrição']

Index = ['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

rename = {}
for old, new in zip(Index, lista):
    rename[old]=new

rename

{'show_id': 'ID',
 'type': 'Tipo',
 'title': 'Título',
 'director': 'Diretor',
 'cast': 'Elenco',
 'country': 'País',
 'date_added': 'Data de adição',
 'release_year': 'Ano de lançamento',
 'rating': 'Classificação',
 'duration': 'duração',
 'listed_in': 'Listado em',
 'description': 'Descrição'}

In [33]:
df = df_netflix.rename(columns=rename)
df.head(3)

,ID,Tipo,Título,Diretor,Elenco,País,Data de adição,Ano de lançamento,Classificação,duração,Listado em
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,"Richard Johnson, Kirsten Johnson, Isla Sierck,...",United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,"Nosipho Dumisa-Ngoasheng, Daryne Joshua, Travi...","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","Belgium, France","September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."

In [12]:
df_netflix = df_netflix.rename(columns = {
    'show_id': 'ID',
    'type': 'Tipo',
    'title': 'Título',
    'director':'Diretor', 
    'cast':'Elenco', 
    'country':'País', 
    'date_added':'Data de adição',
    'release_year':'Ano de lançamento', 
    'rating':'Classificação', 
    'duration':'duração', 
    'listed_in':'Listado em', 
    'description':'Descrição'
})
df_netflix.head(3)

,ID,Tipo,Título,Diretor,Elenco,País,Data de adição,Ano de lançamento,Classificação,duração,Listado em,Descrição
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,"Richard Johnson, Kirsten Johnson, Isla Sierck,...",United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,"Nosipho Dumisa-Ngoasheng, Daryne Joshua, Travi...","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","Belgium, France","September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...

In [15]:
df_netflix = df_netflix.drop(columns = ['Descrição'])
df_netflix.head(3)

,ID,Tipo,Título,Diretor,Elenco,País,Data de adição,Ano de lançamento,Classificação,duração,Listado em
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,"Richard Johnson, Kirsten Johnson, Isla Sierck,...",United States,"September 25, 2021",2020,PG-13,90 min,Documentaries
1,s2,TV Show,Blood & Water,"Nosipho Dumisa-Ngoasheng, Daryne Joshua, Travi...","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries"
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","Belgium, France","September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."

In [18]:
(df_netflix['Tipo'].value_counts(normalize=True)).round(2) * 100

Tipo
Movie      70.0
TV Show    30.0
Name: proportion, dtype: float64

In [24]:
df_netflix['País'].value_counts().head(10)

País
United States               2818
India                       1017
United Kingdom               435
Japan                        274
South Korea                  231
Canada                       187
Spain                        158
United States of America     145
France                       136
Mexico                       122
Name: count, dtype: int64

In [23]:
df_netflix['Ano de lançamento'].value_counts().head(10)

Ano de lançamento
2018    1147
2017    1032
2019    1030
2020     953
2016     902
2021     592
2015     560
2014     352
2013     288
2012     237
Name: count, dtype: int64

In [26]:
df_movie = df_netflix.query('Tipo == "Movie"')
df_movie.shape

(6131, 11)

In [27]:
df_tv_show = df_netflix.query('Tipo == "TV Show"')
df_tv_show.shape

(2676, 11)

In [ ]:
#df_netflix['Data de adição'].dt.strftime('%d/%m/%Y')
df_netflix.head(3)

In [31]:
df_netflix.isna().sum()

ID                      0
Tipo                    0
Título                  0
Diretor              1203
Elenco                296
País                  309
Data de adição         10
Ano de lançamento       0
Classificação           3
duração                 0
Listado em              0
dtype: int64